language: python
python:
- 3.5
before_install:
- rvm install 2.2.5
install:
- pip3 install --upgrade setuptools
- pip3 install coveralls
script:
- python3 setup.py test
after_success:
- coverage run --source=heralding setup.py -q nosetests
- coveralls
deploy:
  provider: pypi
  user: Johnny.Vestergaard
  password:
    secure: liTY6AbvlYX6BcIkir1HPAVkhaLZxRAtcfeSx2Bda76gzbFgAoPnDL7e4RRQ+DtKbsWZp7VeeTIj8XtsS65ctdpVf9hH9V5za7C1N7Ad7nPRqVqxBpJHtRQUT2JmoTn5N0nG1KAt8TNez90lsT8Xe67EbSpWveqDwoSys5LzI/Fx4OjbqbPf3XBYDuM9yojw3USr/In+WgNDQaJpOLe9gPMmkUviTqSLejb1Sb+4T78WxwwmuuN3fC1kXYoKIjFOEdGgfF567JpUDMJ42C011H3MvhV6rhaffYmA77rxPFYAPf2NxD+zxZfEanlUfbSineXqOKmCmMwsBXjpeDqf6zz0Ud6o0y+5YozElOyYni/nBCpI97RSF88NQgbpRZ26OwwvJJz/dIfeK2WeI1nIc+bc1Mw9xJaox8oFaYqkjQMIxRxkhF+A0iFiZ8JEoWqrCawWA3BUlbaictXc6CmYsRLPcVa38hRufeBpX99yHUPjEuHCfJn3v3eU7P6wWUUjDS5JxuaEHe0C6/Ky4Qg2271B+jUDbHD76DDS5uoOKOqHCuSef6pfwxoDG1337legD3LbQr9VCWntZliT84DRKWiG4RsWyYsEunSXnXqmGpvegsvVNaxDm+ZnzNCwi8kBa16zDU65LM2n98jszMjh9w1IekTlJoF0hmh3QvAXcc8=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: johnnykv/heralding
    condition: $TRAVIS_TAG =~ ^Release_[0-9]+[.][0-9]+[.][0-9]+
