#! /bin/sh
### BEGIN INIT INFO
# Provides:          beeswarm
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Init script for Beeswarm <https://github.com/honeynet/beeswarm>
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin
DESC="Beeswarm Honeytoken System"
NAME=beeswarm
DAEMON=/usr/local/bin/$NAME
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

#
# Function that starts the daemon/service
#
do_start()
{
    # Return
    #   0 if daemon has been started
    #   1 if daemon was already running
    #   2 if daemon could not be started
    mkdir -p /opt/beeswarm
    cp /lib/live/mount/medium/dummy.tar.gz /opt/beeswarm
    cd /opt/beeswarm
    tar -xf dummy.tar.gz 2>/dev/null || true
    rm dummy.tar.gz
    beeswarm -v --config beeswarmcfg.json
}


#
# Function that stops the daemon/service
#
do_stop()
{
    # Return
    #   0 if daemon has been stopped
    #   1 if daemon was already stopped
    #   2 if daemon could not be stopped
    #   other if a failure occurred
    pkill `pidof beeswarm`
    rm -f $PIDFILE
    return "$RETVAL"
}


case "$1" in
  start)
    do_start
    ;;
  stop)
    do_stop
    ;;
  restart|force-reload|status|reload)
    echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
    exit 1
    ;;
esac

:
